name: main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - run: bun install --frozen-lockfile

      - run: bun test

      - run: bunx biome check .

      - run: npm run build

      - name: move images
        run: mv doc/images dist/images

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: dist

  deploy:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/deploy-pages@v2

  analyze-bundle:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: github-pages

      - run: tar -xvf artifact.tar

      - name: test the bundle against the report endpoint
        run: |
          curl --silent --show-error --max-time 120 --connect-timeout 120 --retry 3  -X POST --form bundle=@bundle.zip --form category=desktop https://wdbnnia6lj.execute-api.eu-west-1.amazonaws.com/stage/analyze-bundle > report.json

      - run: cat report.json

      - name: fails if the report failed
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            let content = fs.readFileSync("./report.json").toString();
            content = content.replaceAll('{"message": "Endpoint request timed out"}','');
            const report = JSON.parse(content);

            console.log(JSON.stringify(report, null, 2));

            for (const c of require("./report.json").checks)
              if (c.result !== "ok") {
                console.error(c);
                throw c.description;
              }
